#!/bin/bash

echo "Iniciando validação do estágio PRE-COMMIT: \n"

SOURCE_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

BRANCH_PATTERN="^(feature|short-release|short-release!|release!|release|hotfix).*"

if ! [[ $SOURCE_BRANCH_NAME =~ $BRANCH_PATTERN ]]; then
    echo "Erro: O nome da branch '$SOURCE_BRANCH_NAME' não segue as convenções de nomenclatura."
    echo "Os nomes das branches devem começar com: feature, short-release, short-release!, release!, release, ou hotfix."
    exit 1
fi

exit 0